services:
  nginx:
    build: .
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - php-fpm
    networks:
      - webnet
    restart: unless-stopped

  php-fpm:
    image: php:8.2-fpm
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
    driver: bridge
